### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dcode** [CiscoSecurity/fp-05-firepower-cef-connector-arcsight#3]
The license for this states
```
ALL RIGHTS RESERVED. THESE SOURCE FILES ARE THE SOLE PROPERTY
OF CISCO SYSTEMS, Inc. AND CONTAIN CONFIDENTIAL  AND PROPRIETARY
INFORMATION.  REPRODUCTION OR DUPLICATION BY ANY MEANS OF ANY
PORTION OF THIS SOFTWARE WITHOUT PRIOR WRITTEN CONSENT OF
CISCO SYSTEMS, Inc. IS STRICTLY PROHIBITED.
```

This seems to suggest that no one is authorized without having an explicit license approval from Cisco? I came across this looking for a utility to connect to an eStreamer application and output JSON that I can push to Logstash. Is there a universe where I'd be able to use this code for that purpose?

**Comment by nicpenning** [comment]
Same, how do we go about using this code?

**Comment by nicpenning** [comment]
I found this in their documentation here: https://www.cisco.com/c/en/us/td/docs/security/firepower/630/api/eStreamer_enCore/eStreamereNcoreCLIOperationsGuide_354.html

The application is free to use and is community supported.  Questions can be emailed to encore-community@cisco.com.  A paid and TAC supported version is available by ordering FP-CEF-SW-K9.

**Comment by nicpenning** [comment]
@dcode They updated the license: https://github.com/CiscoSecurity/fp-05-firepower-cef-connector-arcsight/commit/64d56e9a17cabceaf2e42e46fc7a78b604fd53a9
